// Curates the board's icon set from Fluent Emoji Flat (MIT, Microsoft) and
// writes lib/board-icons.generated.ts. Re-run after changing the list:
//   npx tsx scripts/build-icons.ts
import fs from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const data = require("@iconify-json/fluent-emoji-flat/icons.json") as {
  width?: number;
  height?: number;
  icons: Record<string, { body: string; width?: number; height?: number; left?: number; top?: number }>;
};

// Friendly name the tutor uses → Fluent Emoji Flat icon name.
const CURATED: Record<string, string> = {
  // food
  apple: "red-apple", green_apple: "green-apple", banana: "banana", orange: "tangerine", strawberry: "strawberry", grapes: "grapes",
  watermelon: "watermelon", cherries: "cherries", lemon: "lemon", pear: "pear", peach: "peach", carrot: "carrot", broccoli: "broccoli",
  potato: "potato", corn: "ear-of-corn", pizza: "pizza", burger: "hamburger", hot_dog: "hot-dog", fries: "french-fries", taco: "taco",
  sandwich: "sandwich", bread: "bread", egg: "egg", cheese: "cheese-wedge", cookie: "cookie", cake: "birthday-cake", cupcake: "cupcake",
  donut: "doughnut", candy: "candy", lollipop: "lollipop", chocolate: "chocolate-bar", ice_cream: "ice-cream", popcorn: "popcorn",
  milk: "glass-of-milk", cup: "hot-beverage", juice: "cup-with-straw",
  // money
  coin: "coin", dollar: "dollar-banknote", money_bag: "money-bag", credit_card: "credit-card",
  // animals
  dog: "dog", cat: "cat", rabbit: "rabbit", bird: "bird", fish: "fish", cow: "cow", chicken: "chicken", pig: "pig", horse: "horse",
  bee: "honeybee", butterfly: "butterfly", ant: "ant", frog: "frog", turtle: "turtle",
  // play
  soccer_ball: "soccer-ball", basketball: "basketball", baseball: "baseball", tennis_ball: "tennis", balloon: "balloon", gift: "wrapped-gift",
  trophy: "trophy", ticket: "ticket",
  // school and objects
  book: "open-book", books: "books", pencil: "pencil", backpack: "backpack", ruler: "straight-ruler", scissors: "scissors",
  calendar: "calendar", clock: "alarm-clock", watch: "watch", light_bulb: "light-bulb", key: "key", bell: "bell", star: "star",
  heart: "red-heart", candle: "candle", umbrella: "umbrella", magnet: "magnet", battery: "battery", phone: "telephone", laptop: "laptop",
  tv: "television", camera: "camera", chair: "chair", door: "door", window: "window",
  // places and transport
  house: "house", school: "school", bus: "bus", car: "automobile", bicycle: "bicycle", truck: "delivery-truck", airplane: "airplane",
  train: "locomotive", rocket: "rocket", boat: "sailboat",
  // nature
  tree: "deciduous-tree", flower: "tulip", sun: "sun", cloud: "cloud", rain: "cloud-with-rain", snowflake: "snowflake", moon: "crescent-moon",
  lightning: "high-voltage", fire: "fire", droplet: "droplet", leaf: "fallen-leaf",
  // people
  person: "bust-in-silhouette", boy: "boy", girl: "girl", teacher: "teacher", student: "student",
  // containers
  box: "package", basket: "basket", cart: "shopping-cart", jar: "jar", bag: "shopping-bags",
};

const out: Record<string, { body: string; w: number; h: number }> = {};
const missing: string[] = [];
for (const [friendly, name] of Object.entries(CURATED)) {
  const icon = data.icons[name];
  if (!icon) {
    missing.push(`${friendly} (${name})`);
    continue;
  }
  out[friendly] = { body: icon.body, w: icon.width ?? data.width ?? 32, h: icon.height ?? data.height ?? 32 };
}
if (missing.length) {
  console.error("Missing icons:", missing.join(", "));
  process.exit(1);
}
const names = Object.keys(out);
const file = `// GENERATED by scripts/build-icons.ts. Do not edit by hand.
//
// Icons: Fluent Emoji (Microsoft), flat style, via @iconify-json/fluent-emoji-flat.
// MIT License. Copyright (c) Microsoft Corporation.
// https://github.com/microsoft/fluentui-emoji/blob/main/LICENSE

import type { BoardIconName } from "./board-icon-names.generated";

export type BoardIcon = { body: string; w: number; h: number };

export const BOARD_ICONS: Record<BoardIconName, BoardIcon> = ${JSON.stringify(out)};
`;
fs.writeFileSync("lib/board-icons.generated.ts", file);
// Names only, for the tool declaration and the dispatcher (no SVG bodies on the server).
fs.writeFileSync(
  "lib/board-icon-names.generated.ts",
  `// GENERATED by scripts/build-icons.ts. Do not edit by hand.\nexport const BOARD_ICON_NAMES = ${JSON.stringify(names)} as const;\nexport type BoardIconName = (typeof BOARD_ICON_NAMES)[number];\n`,
);
console.log(`wrote lib/board-icons.generated.ts with ${names.length} icons, ${Math.round(file.length / 1024)} KB`);
