// Generated by scripts/landing-shots.mjs. Do not edit; rerun the script.
export const SHOTS = {
  steps: { src: "/landing/steps.png", width: 877, height: 683 },
  hint: { src: "/landing/hint.png", width: 628, height: 478 },
  worksheet: { src: "/landing/worksheet.png", width: 654, height: 440 },
  hero: { src: "/landing/session-board.png", width: 2136, height: 1280 },
} as const;
