// Generated by scripts/landing-shots.mjs. Do not edit; rerun the script.
export const SHOTS = {
  steps: { src: "/landing/steps.png", width: 877, height: 614 },
  hint: { src: "/landing/hint.png", width: 695, height: 515 },
  worksheet: { src: "/landing/worksheet.png", width: 1572, height: 1154 },
  graph: { src: "/landing/graph.png", width: 952, height: 915 },
  figure: { src: "/landing/figure.png", width: 614, height: 673 },
  icons: { src: "/landing/icons.png", width: 1052, height: 475 },
  fraction: { src: "/landing/fraction.png", width: 963, height: 525 },
  hero: { src: "/landing/session-board.png", width: 2136, height: 1280 },
  compare: { src: "/landing/compare.png", width: 1799, height: 846, frames: ["/landing/compare-2.png", "/landing/compare-4.png", "/landing/compare-6.png", "/landing/compare-9.png"] },
  negatives: { src: "/landing/negatives.png", width: 1160, height: 367 },
  slope: { src: "/landing/slope.png", width: 952, height: 826 },
  percent: { src: "/landing/percent.png", width: 720, height: 777 },
  area: { src: "/landing/area.png", width: 700, height: 451 },
  solved: { src: "/landing/solved.png", width: 740, height: 594 },
  ratio: { src: "/landing/ratio.png", width: 1109, height: 371 },
} as const;
