// Generated by scripts/landing-shots.mjs. Do not edit; rerun the script.
export const SHOTS = {
  steps: { src: "/landing/steps.png", width: 873, height: 614 },
  hint: { src: "/landing/hint.png", width: 695, height: 515 },
  worksheet: { src: "/landing/worksheet.png", width: 705, height: 440 },
  hero: { src: "/landing/session-board.png", width: 2136, height: 1280 },
} as const;
